// Package qrcode encodes bytes as a QR Code symbol (ISO/IEC 18004, Model 2): byte mode,
// error correction level L, M, Q or H, the smallest of versions 1-40 that holds the data,
// Reed-Solomon error correction, the mask the standard's four penalty rules score lowest,
// and the format and (version 7 and up) version information. It returns the module matrix;
// drawing it is the caller's (operatorpages draws the operator enrollment key's QR code as
// one SVG path -- ADR 0020 §3, QR note).
//
// WHY IN THE REPOSITORY, NOT A LIBRARY. The user decided on 2026-10-09 that the enrollment
// page shows its key as a QR code; CLAUDE.md §1 adds no dependency for it ("stdlib > small
// library"). This package imports the standard library only.
//
// WHAT IT KEEPS AND PRINTS: nothing. Its one caller hands it an otpauth:// URI, which
// carries a TOTP secret. Encode holds no state between calls, writes no log, and its errors
// name lengths and levels, never content (TestEncode_TheRefusalCarriesNoInput). The matrix
// it returns IS the input, in another form -- it is as secret as the URI.
//
// KNOWN-ANSWER PROOF, NOT SELF-CONSISTENCY. An encoder and a decoder written from one
// misreading of the standard agree with each other and with nobody else. The tests hold
// the output to matrices libqrencode 4.1.1 made (testdata/, generated by
// testdata/generate.sh, which the tests do not run), and read it back with a decoder that
// shares no code or table with this file (read_test.go).
package qrcode

import (
	"errors"
	"fmt"
)

// Level is an error correction level. The constants' order is the standard's order of
// strength; the two bits the format information carries for each are formatBits'.
type Level int

const (
	L Level = iota // about 7% of the codewords recoverable
	M              // about 15%
	Q              // about 25%
	H              // about 30%
)

func (l Level) String() string {
	switch l {
	case L:
		return "L"
	case M:
		return "M"
	case Q:
		return "Q"
	case H:
		return "H"
	}
	return fmt.Sprintf("Level(%d)", int(l))
}

func (l Level) valid() bool { return l >= L && l <= H }

// formatBits is the level's indicator in the format information (ISO/IEC 18004 Table 12):
// L 01, M 00, Q 11, H 10 -- not the constants' order.
func (l Level) formatBits() int { return [...]int{1, 0, 3, 2}[l] }

const (
	// MinVersion and MaxVersion bound the versions Encode chooses from.
	MinVersion = 1
	MaxVersion = 40
	// QuietZone is the light border the standard requires around a symbol, in modules
	// (ISO/IEC 18004 §5.3.8: 4X). Bitmap adds it; Size does not count it.
	QuietZone = 4
)

// ErrTooLong is the refusal of data no version-40 symbol at the level holds. The wrapping
// error adds the input's length and the level's limit -- never the input.
var ErrTooLong = errors.New("qrcode: the data does not fit a version 40 symbol at this level")

var errLevel = errors.New("qrcode: unknown error correction level")

// Code is an encoded symbol: a square of Size() modules, without the quiet zone.
type Code struct {
	version int
	level   Level
	mask    int
	modules [][]bool // [y][x]; true is dark
}

// Version is the symbol's version, 1-40; its side is 17 + 4*Version modules.
func (c *Code) Version() int { return c.version }

// Level is the error correction level the symbol was encoded at.
func (c *Code) Level() Level { return c.level }

// Mask is the data mask pattern applied, 0-7.
func (c *Code) Mask() int { return c.mask }

// Size is the symbol's side in modules, the quiet zone not counted.
func (c *Code) Size() int { return len(c.modules) }

// Dark reports whether the module at column x, row y is dark. Outside the symbol -- the
// quiet zone and beyond -- every module is light.
func (c *Code) Dark(x, y int) bool {
	if y < 0 || y >= len(c.modules) || x < 0 || x >= len(c.modules) {
		return false
	}
	return c.modules[y][x]
}

// Bitmap is the symbol with border light modules added on each side, as a fresh matrix
// indexed [y][x], true dark. Bitmap(QuietZone) is what a reader must be shown.
func (c *Code) Bitmap(border int) [][]bool {
	border = max(border, 0)
	side := len(c.modules) + 2*border
	out := make([][]bool, side)
	for y := range out {
		out[y] = make([]bool, side)
		for x := range out[y] {
			out[y][x] = c.Dark(x-border, y-border)
		}
	}
	return out
}

// Encode encodes data in byte mode at level, in the smallest version that holds it, with
// the mask of lowest penalty (the lowest-numbered on a tie). Data no version-40 symbol at
// level holds is refused with an error wrapping ErrTooLong.
func Encode(data []byte, level Level) (*Code, error) {
	return encode(data, level, MinVersion, -1)
}

// encode is Encode with the smallest version allowed and the mask forced (0-7) or chosen
// (-1): the tests compare against a reference made at a chosen version, and hold each of
// the eight masks to the reference's matrix.
func encode(data []byte, level Level, minVersion, mask int) (*Code, error) {
	if !level.valid() {
		return nil, errLevel
	}
	if mask < -1 || mask > 7 || minVersion < MinVersion || minVersion > MaxVersion {
		return nil, errors.New("qrcode: version or mask out of range")
	}
	ver := 0
	for v := minVersion; v <= MaxVersion; v++ {
		if len(data) <= capacity(v, level) {
			ver = v
			break
		}
	}
	if ver == 0 {
		return nil, fmt.Errorf("%w (%d bytes; level %s holds at most %d)", ErrTooLong, len(data), level, capacity(MaxVersion, level))
	}
	g := newGrid(ver)
	g.drawFunctionPatterns()
	g.placeData(interleave(dataCodewords(data, ver, level), ver, level))
	if mask < 0 {
		mask = g.bestMask(level)
	}
	g.applyMask(mask)
	g.drawFormat(level, mask)
	return &Code{version: ver, level: level, mask: mask, modules: g.dark}, nil
}

// countBits is the width of byte mode's character count indicator (ISO/IEC 18004
// Table 3): 8 bits up to version 9, 16 from version 10.
func countBits(ver int) int {
	if ver <= 9 {
		return 8
	}
	return 16
}

// capacity is the most bytes a version-ver symbol at level holds in byte mode: the data
// codewords' bits less the mode indicator (4) and the count, whole bytes.
func capacity(ver int, level Level) int {
	return (numDataCodewords(ver, level)*8 - 4 - countBits(ver)) / 8
}

// dataCodewords is the data bit stream of ISO/IEC 18004 §7.4: byte mode's indicator 0100,
// the count, the bytes, a terminator of up to four zero bits, zero bits to a byte boundary,
// and the pad codewords 11101100 and 00010001 in turn up to the version's data capacity.
func dataCodewords(data []byte, ver int, level Level) []byte {
	n := numDataCodewords(ver, level)
	var b bitWriter
	b.write(0b0100, 4)
	b.write(len(data), countBits(ver))
	for _, c := range data {
		b.write(int(c), 8)
	}
	b.write(0, min(4, n*8-b.n))
	b.write(0, (8-b.n%8)%8)
	out := b.buf
	for pad := byte(0xEC); len(out) < n; pad ^= 0xEC ^ 0x11 {
		out = append(out, pad)
	}
	return out
}

// bitWriter appends bits, most significant first.
type bitWriter struct {
	buf []byte
	n   int // bits written
}

func (b *bitWriter) write(v, bits int) {
	for i := bits - 1; i >= 0; i-- {
		if b.n%8 == 0 {
			b.buf = append(b.buf, 0)
		}
		if v>>i&1 == 1 {
			b.buf[b.n/8] |= 0x80 >> (b.n % 8)
		}
		b.n++
	}
}

// interleave splits the data codewords into the version's blocks, appends each block's
// Reed-Solomon codewords and interleaves them (ISO/IEC 18004 §7.5-7.6): the data
// codewords column by column across the blocks -- the shorter blocks come first and lack
// the last column -- then the error correction codewords the same way.
func interleave(data []byte, ver int, level Level) []byte {
	blocks := numBlocks[level][ver]
	eccLen := eccPerBlock[level][ver]
	raw := numRawDataModules(ver) / 8
	short := blocks - raw%blocks
	shortLen := raw/blocks - eccLen // data codewords in a short block
	divisor := rsDivisor(eccLen)
	dat := make([][]byte, blocks)
	ecc := make([][]byte, blocks)
	k := 0
	for i := range blocks {
		n := shortLen
		if i >= short {
			n++
		}
		dat[i] = data[k : k+n]
		ecc[i] = rsRemainder(dat[i], divisor)
		k += n
	}
	out := make([]byte, 0, raw)
	for col := 0; col <= shortLen; col++ {
		for i := range blocks {
			if col < len(dat[i]) {
				out = append(out, dat[i][col])
			}
		}
	}
	for col := range eccLen {
		for i := range blocks {
			out = append(out, ecc[i][col])
		}
	}
	return out
}
