// Command seedkeys completes test/fixtures/seed.sql by giving every demo plaque a
// genuinely KEK-WRAPPED per-tag key, and it emits SQL rather than touching the
// database itself.
//
// WHY THE SEED CANNOT DO THIS IN SQL. tags.aes_key_ref is an AES-256-GCM envelope
// (ADR 0003 madde 4): nonce(12) || ciphertext(16) || gcm_tag(16) = 44 bytes,
// sealed under TAPPA_TAG_KEK with the raw 7-byte UID as AAD. Postgres cannot
// produce it — pgcrypto has no GCM — and it could not be a literal anyway,
// because the value depends on the operator's KEK, which lives in the environment
// and never in the repository (CLAUDE.md §4.7). Before this step the fixture held
// 42 bytes of ASCII placeholder and every NFC tap on a seeded plaque answered 500
// from sun.Unwrap ("wrapped ref must be 44 bytes, got 42").
//
// WHY IT PRINTS SQL INSTEAD OF CONNECTING. The seed's write authority is
// tappa_owner, established by scripts/seed.sh; a Go step with its own connection
// would either duplicate that decision or quietly demote the write to tappa_app
// and drag RLS, SET LOCAL and a second pool into a fixture tool. Printing SQL
// keeps this program a pure function of (KEK, fixture list) — no database driver,
// no credentials, no network — and leaves the role question exactly where
// scripts/seed.sh already answered it.
//
// SECRETS. The only key material that reaches stdout is the WRAPPED blob, which
// is the form the column is meant to hold. The KEK is read from the environment
// and never printed; the plaintext per-tag keys are derived from a public,
// deliberately loud label (fixtures.SeedTagKeyLabel) and are never printed
// either — anybody who needs one recomputes it from the label, which is what
// makes these keys self-evidently fake.
package main

import (
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"os"
	"strings"

	"github.com/atknatk/tappa/internal/sun"
	"github.com/atknatk/tappa/test/fixtures"
)

// kekEnv is the same variable internal/config reads into Config.TagKEK. It is
// read directly here rather than through config.Load because that would demand
// every OTHER required variable (database URLs, HMAC keys, retention years) just
// to wrap twelve fixture keys.
const kekEnv = "TAPPA_TAG_KEK"

func main() {
	if err := run(os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "seedkeys: %v\n", err)
		os.Exit(1)
	}
}

func run(out *os.File) error {
	raw := os.Getenv(kekEnv)
	if raw == "" {
		// TWO different mistakes end up here and the message has to name both:
		// the variable may be missing from the shell, or it may never have been
		// GENERATED at all (.env.example ships it empty). Saying only "export it"
		// sends a first-time developer looking for a value that does not exist.
		return fmt.Errorf("%s is empty. Generate one — openssl rand -base64 32 — and put it in .env; "+
			"`make seed` exports .env, a bare shell must export it itself", kekEnv)
	}
	kek, err := base64.StdEncoding.DecodeString(raw)
	if err != nil {
		// The message names the variable and the failure, never the value (§4.7).
		return fmt.Errorf("%s: not valid base64", kekEnv)
	}
	if len(kek) != 32 {
		return fmt.Errorf("%s: want 32 bytes, got %d", kekEnv, len(kek))
	}

	var b strings.Builder
	b.WriteString("-- GENERATED by test/fixtures/seedkeys — do not edit, do not commit.\n")
	b.WriteString("-- Wraps each demo plaque's FAKE per-tag key under the operator's KEK.\n")
	b.WriteString("BEGIN;\n")

	for _, tag := range fixtures.SeedTags {
		uidBytes, err := fixtures.SeedTagUIDBytes(tag.UID)
		if err != nil {
			return err
		}
		key := fixtures.SeedTagKey(tag.UID)
		ref, err := sun.Wrap(kek, uidBytes, key)
		if err != nil {
			return fmt.Errorf("wrap %s: %w", tag.UID, err)
		}
		sun.Zero(key) // the plaintext key's lifetime ends here (§4.7)

		// The UPDATE is UNCONDITIONAL, and that is a choice with a measured
		// consequence: sun.Wrap draws a fresh nonce every call, so running `make
		// seed` twice rewrites all twelve refs with different BYTES that decrypt to
		// the same keys. The alternative — only touching rows that are not already
		// 44 bytes — would be byte-stable but would silently leave a database
		// stranded after a KEK change, which is the failure this whole step exists
		// to remove. Row identity is still idempotent: nothing is inserted, nothing
		// is deleted, and no other column is touched.
		//
		// tenant_id rides along with the primary key on purpose (§4.5,
		// belt-and-braces): the seed runs as tappa_owner, which BYPASSES RLS, so an
		// explicit scope is the only thing standing between a mistyped uid and
		// another tenant's plaque.
		//
		// 🔴 THE STATEMENT IS BUILT BY INTERPOLATION, AND THE BOUNDARY THAT MAKES
		// THAT SAFE IS WRITTEN HERE RATHER THAN ASSUMED. This program has no driver
		// and opens no connection (see the file header), so there is no placeholder
		// to bind to; what keeps the pattern from being an injection is that all
		// three values are structurally constrained BEFORE they reach the format
		// string:
		//
		//	ref        hex.EncodeToString — [0-9a-f]* by construction.
		//	tag.UID    validated by fixtures.SeedTagUIDBytes above, which returns an
		//	           error unless the string decodes as hex to exactly 7 bytes. A
		//	           uid carrying a quote never reaches this line; the loop has
		//	           already returned.
		//	TenantID   uuid.UUID.String() — 36 characters of hex and hyphens.
		//
		// THE BOUNDARY: the moment any of the three comes from somewhere a caller
		// controls — an env var, a CLI argument, a file, a database column — this
		// reasoning is void and concatenation becomes an injection. There is no
		// local fix at that point (no driver, no bind parameters), so the answer
		// would be to move the wrapping into a step that has one, not to add
		// quoting here.
		//
		// R7 LESSON, MEASURED, and the same one nfcURL states for itself: the
		// Fprintf below used to escape redline R7 ("secret logged") only because
		// `aes_key_ref` sits on the NEXT source line and the rule matched line by
		// line — the verdict was right (this writes SQL and logs nothing) but it was
		// right by accident of formatting.
		//
		// 🔴 THAT ACCIDENT IS GONE (M8-03 round 4): R7 now scans with `rg -U` and a
		// balanced-paren window, so this region IS matched, and it is exempted BY
		// NAME instead — scripts/redline-check.sh's R7_WAIVERS lists this path with
		// the single benign token `aes_key_ref`, and the exemption is printed as a
		// WARN on every run. Two consequences worth knowing before editing this
		// block: joining the lines changes nothing any more, and adding a REAL
		// never-log value here (a token, a cmac, a raw key) still fails the scan,
		// because the waiver only forgives the named token and re-tests what is left.
		fmt.Fprintf(&b,
			"UPDATE tags SET aes_key_ref = '\\x%s'::bytea WHERE uid = '%s' AND tenant_id = '%s'::uuid;\n",
			hex.EncodeToString(ref), tag.UID, tag.TenantID)
	}

	// DRIFT GUARD. If somebody adds a plaque to seed.sql and forgets
	// fixtures.SeedTags, the row keeps its ASCII placeholder and the FIRST person
	// to tap it gets a 500 — days later, far from the change. This makes that
	// mistake fail here instead, loudly, at seed time.
	//
	// 🔴 IT ASKS ABOUT BYTES, NOT LENGTH — AND THAT IS A CORRECTION, MEASURED.
	// Migration 00021's tags_aes_key_ref_is_kek_envelope demands
	// octet_length(aes_key_ref) = 44 of every row, so seed.sql's placeholder label
	// was padded to 30 characters (30 + a 14-hex uid = 44). A length-only guard
	// therefore stopped seeing the ONE mistake it was written for. Probed on the
	// development database, a plaque added to the KF tenant with its placeholder
	// intact, running the emitted DO block verbatim:
	//
	//	04AC7E55009901 | placeholder_len = 44
	//	NOTICE: seedkeys guard PASSED -- forgotten plaque NOT detected
	//
	// Nothing else covered it either: internal/handler/seedflow_db_test.go's key
	// loop walks fixtures.SeedTags, and a plaque that was forgotten in SeedTags is
	// by definition not in that list, so it is never visited. seed.sql's plaque
	// list is a hand-written VALUES block and is not derived from SeedTags, so the
	// drift is real rather than theoretical.
	//
	// THE THREE PREDICATES, and why it is three and not one:
	//   * octet_length <> 44 — the original. Still the only thing that catches a
	//     plaque loaded by some path the CHECK does not police.
	//   * the placeholder's BYTES — seed.sql's exact label, single-sourced as
	//     fixtures.SeedPlaceholderKeyLabel. This is what closes the measured hole,
	//     and it names the mistake precisely in the message.
	//   * "is the value ASCII TEXT at all" — encode(...,'escape') expands any
	//     non-printable byte to a backslash escape, so length(encode(v,'escape'))
	//     equals octet_length(v) only when every byte is printable. This is the
	//     net under the previous predicate: seed.sql cannot import a Go constant,
	//     so if somebody reworded the label there and not here, the label match
	//     would go quiet and this would not. MEASURED on the real column: the
	//     44-byte placeholder -> true; 44 bytes from gen_random_bytes -> false;
	//     and across the 26 tag rows the two demo tenants currently hold, 0 match
	//     it (i.e. no genuine envelope is a false positive). A real envelope is
	//     ciphertext, so the odds of one being 44 printable bytes are about
	//     (94/256)^44, which is 1e-19.
	//
	// IT IS SCOPED TO THE TWO DEMO TENANTS, and the reason is a LENGTH, not a key.
	// An earlier version of this comment said an unscoped guard would trip over
	// test-created plaques "already wrapped under a different KEK"; MEASURED, that
	// names the half of the population that does NOT matter. Rows wrapped under a
	// test KEK really are 44 bytes and sail straight through a length check. What
	// used to trip it was the two-byte marker `'\xDEAD'` the DB fixtures inserted
	// wholesale (internal/db/rls_test.go, internal/db/store_test.go,
	// internal/sun/advance_test.go). Measured on a freshly reset dev database, one
	// `make test` later: 68 tag rows at 2 bytes and 184 at 44 (12 of them seeded).
	// So an unscoped guard would refuse to seed any database a developer has run
	// the suite against even once. Those fixtures now write 44 bytes of nonsense
	// (00021 refuses anything else), so the residue stops growing — but 45 728
	// two-byte rows written before that change still exist on this machine, which
	// is why the scope stays where it is.
	//
	// 🔴 THE SCOPE IS THE FIXED TENANT PAIR, NOT "whatever tenants SeedTags
	// mentions", and the difference was MEASURED rather than reasoned about. The
	// first version derived the list from SeedTags; deleting the KM plaque from
	// SeedTags therefore also deleted KM from the guard's scope, and the seed went
	// green with a broken plaque in the database — a guard that stops looking
	// exactly where the mistake was made. Deriving the scope from the same drifting
	// value it is meant to police is the bug; the tenants are stable master data,
	// so they are named.
	quoted := []string{
		"'" + fixtures.TenantKF.String() + "'::uuid",
		"'" + fixtures.TenantKM.String() + "'::uuid",
	}
	// The placeholder comparison is built ONCE and used TWICE below (as a
	// predicate and as the diagnosis), so the row that trips the guard and the
	// sentence explaining why cannot disagree. The label is a compile-time
	// constant of this repository, never caller input, so the interpolation
	// boundary written above still holds.
	placeholderBytes := fmt.Sprintf(
		"substring(aes_key_ref from 1 for %d) = convert_to('%s', 'UTF8')",
		len(fixtures.SeedPlaceholderKeyLabel), fixtures.SeedPlaceholderKeyLabel)

	fmt.Fprintf(&b, `DO $$
DECLARE stragglers text;
BEGIN
    SELECT string_agg(uid || ' [' || reason || ']', ', ' ORDER BY uid) INTO stragglers
      FROM (
        SELECT uid,
               CASE WHEN octet_length(aes_key_ref) <> 44
                         THEN 'wrong length: ' || octet_length(aes_key_ref) || ', want 44'
                    WHEN %[1]s
                         THEN 'still carries the seed.sql placeholder'
                    ELSE 'value is printable text, not an encrypted envelope'
               END AS reason
          FROM tags
         WHERE tenant_id IN (%[2]s)
           AND (octet_length(aes_key_ref) <> 44
                OR %[1]s
                OR octet_length(aes_key_ref) = length(encode(aes_key_ref, 'escape')))
      ) s;
    IF stragglers IS NOT NULL THEN
        RAISE EXCEPTION 'seedkeys: demo plaque(s) left without a real KEK-wrapped key: %%. Add them to fixtures.SeedTags and re-run the seed.', stragglers;
    END IF;
END $$;
`, placeholderBytes, strings.Join(quoted, ", "))

	b.WriteString("COMMIT;\n")
	_, err = out.WriteString(b.String())
	return err
}
