package httpx_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/atknatk/tappa/internal/config"
	"github.com/atknatk/tappa/internal/httpx"
)

// The static asset surface. Files are served; DIRECTORIES are not.
//
// http.FileServer renders an index page for any directory it can open, and an
// audit measured what that meant once M5-04 added real asset directories:
// GET /static/fonts/ answered 200 with a full file listing. Nothing secret is
// in there, so this is surface reduction rather than a leak — but a listing is a
// free inventory of what a deployment ships, and the directory only grows.
func TestStatic_ServesFilesButNotDirectoryListings(t *testing.T) {
	srv := httptest.NewServer(httpx.NewRouter(&config.Config{}))
	t.Cleanup(srv.Close)

	get := func(path string) (int, string) {
		t.Helper()
		resp, err := http.Get(srv.URL + path)
		if err != nil {
			t.Fatalf("GET %s: %v", path, err)
		}
		defer resp.Body.Close()
		buf := make([]byte, 4096)
		n, _ := resp.Body.Read(buf)
		return resp.StatusCode, string(buf[:n])
	}

	// POSITIVE CONTROL FIRST: a real file still serves. Without this, every
	// assertion below would also pass against a router that served nothing.
	// tap.js is used rather than app.css because app.css is generated by
	// `make css` and is not in version control.
	if code, body := get("/static/js/tap.js"); code != http.StatusOK {
		t.Fatalf("GET /static/js/tap.js = %d, want 200 — the asset route is broken, so the "+
			"refusals below prove nothing", code)
	} else if !strings.Contains(body, "getCurrentPosition") {
		t.Fatal("the served script is not the tap script")
	}

	// Directories, with and without the trailing slash, and the root.
	for _, dir := range []string{"/static/", "/static/fonts/", "/static/js/", "/static/fonts", "/static/css/"} {
		code, body := get(dir)
		if code == http.StatusOK {
			t.Fatalf("GET %s = 200 with a body of %d bytes: directory listing is open", dir, len(body))
		}
		for _, leaked := range []string{"woff2", "tap.js", "OFL"} {
			if strings.Contains(body, leaked) {
				t.Fatalf("GET %s leaked a filename (%q) in a %d response", dir, leaked, code)
			}
		}
	}
}
