// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/atknatk/tappa/web/templates/components"

// The LOCATIONS section — the panel's answer to "where do we work, and what counts
// as being there?" (M6-06 phase A).
//
// 🔴 IT RENDERS PanelShell, NOT PanelShellWithScript, AND THAT IS THE WHOLE SCRIPT
// DECISION. PanelShell has no script slot (user decision, 2026-08-06: the split
// exists so that giving a section a script is a COMPILE error rather than an edit to
// a string), so this section could not load one without naming a different component
// on purpose. It does not need to: every control here is a link, a form field or a
// submit button. The one place a script would have helped is the address-range
// repeater, and that is a textarea instead — the trade is written down at
// components.VenueFormView.Ranges rather than felt.
//
// 🔴 §4.7 — NOTHING BELOW RENDERS A SECRET, AND THE VIEW MODEL IS WHY. LocationsView
// has no field for a key, a token, a hash or an employee name, so this template
// could not print one. The Wi-Fi network name IS rendered and is not a secret:
// migration 00010 argues that at length — it is the network a venue publishes to its
// own staff, and it is explicitly not evidence of anything.
//
// 🔴 §4.6 — THE EMPTY STATE IS GATED ON HAVING ASKED. "This business has no venues"
// is a claim about a business and the product may not make one it has not measured;
// v.Queried is set only after the database answered, and a failed read renders a
// problem page in the handler rather than an empty list here.
//
// 🔴 THE CONTROLS ARRIVED WITH THEIR HANDLERS. A screen offering something the
// server does not implement is this repository's most expensive class of mistake,
// and it takes two nets because it has two halves:
//
//	does the control lead somewhere SERVED?   TestLocationsSection_
//	  EveryControlLeadsSomewhereThatExists drives every form target and every link
//	  on this page through the real router.
//	would the server REFUSE what it offers?   TestLocationsSection_
//	  OffersNoActionTheServerWouldRefuse requires the department form's venue
//	  control to be ABSENT when editing — because UpdateDepartment cannot move one —
//	  with the sentence that explains it present, and a NEW department's form as the
//	  control.
func AdminLocations(v LocationsView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			if v.RemovalReceipt != nil {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "     ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>It is gone from the list below. Its records are kept — nothing that already happened there has changed, and the removal itself is in the audit trail.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneOK, removalHeading(v.Done, v.RemovalReceipt.Name)).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if v.Done != "" && !ClaimsARemoval(v.Done) && !ClaimsAPlaqueAct(v.Done) {
				templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					switch v.Done {
					case "venue-added", "venue-saved":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "     <p>The venue below is as it now stands. Check its address ranges and coordinate — they are what taps here are checked against.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					default:
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p>The department below is as it now stands.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneOK, doneVenueHeading(v.Done)).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.Problem != "" {
				templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					switch v.Problem {
					case "unreadable":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<p>We could not read that submission, so nothing was changed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "unknown-venue":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<p>That venue is not one of this business's. Nothing was changed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "unknown-department":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<p>That department is not one of this business's. Nothing was changed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "venue-in-use", "department-in-use":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "   <p>Something was added to it while you were looking, so it is no longer empty and nothing was removed. Open it again to see what is there now.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "not-permitted":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "   <p>Removing a venue or a department cannot be undone, so it is reserved for an owner. Nothing was removed — ask one of your business's owners.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "confirm-required":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<p>Removing something asks first. Nothing was removed — open it again and use the remove link.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "confirm-stale":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<p>That confirmation was for something else — you may have opened another one in the meantime. Nothing was removed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "unknown-plaque":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<p>That plaque id is not one of this business's. Nothing was changed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "plaque-not-stock":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "    <p>Somebody mounted that spare while you were looking, so nothing was changed. Open the plaque again and pick another spare.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "plaque-not-active":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<p>That plaque is not on a wall any more — somebody may have replaced it already. Nothing was changed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "plaque-no-wall":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<p>That plaque is not on a wall, so there is nothing to take down. Nothing was changed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "same-plaque":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<p>A plaque cannot replace itself. Nothing was changed — pick a spare from the box.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					case "plaque-frozen":
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "    <p>That plaque's id was recorded in a spelling this system no longer accepts, so nothing can be written to it. Nothing was changed.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					default:
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<p>We could not load your venues. Nothing was changed — try again in a moment.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneWarn, problemVenueHeading(v.Problem)).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.PlaqueReceipt != nil {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "      ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					if v.PlaqueReceipt.Unmounted {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "<p>It is back in stock, ready to mount somewhere else. Nothing was retired and no spare was used — but a tap at that door is rejected until you put a plaque up there.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else if v.PlaqueReceipt.Replaced {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "<p>The old plaque is retired and its record stays — every tap it ever took still resolves. A tap on it now is rejected, so take it off the wall.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "<p>The plaque is now in service. From now on a tap on it is a tap at that place.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneOK, plaqueHeading(*v.PlaqueReceipt)).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.VenueForm != nil {
				templ_7745c5c3_Err = components.VenueForm(*v.VenueForm).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.DepartmentForm != nil {
				templ_7745c5c3_Err = components.DepartmentForm(*v.DepartmentForm).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.PlaqueForm != nil {
				templ_7745c5c3_Err = components.PlaqueCard(*v.PlaqueForm).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, " <section class=\"flex flex-col gap-4\"><div class=\"flex flex-wrap items-center justify-between gap-3\"><h2 class=\"font-display text-lg font-bold tracking-tight text-ink\">Venues</h2><a class=\"btn btn--primary\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 templ.SafeURL = templ.URL(v.AddVenueHref)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var7)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "\">Add a venue</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.VenuesCapped {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "  ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Var8 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "<p>Only the first ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var9 string
					templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(v.VenueLimit)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/pages/locations.templ`, Line: 161, Col: 35}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, " venues are shown. If your business really has more than this, tell us — the screen was built for an estate of tens, not hundreds.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneWarn, "This list is not complete").Render(templ.WithChildren(ctx, templ_7745c5c3_Var8), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if len(v.Venues) > 0 {
				for _, ven := range v.Venues {
					templ_7745c5c3_Err = components.VenueRow(ven).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else if v.Queried {
				templ_7745c5c3_Var10 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "    <p>No venues have been added to this business yet. A venue is a place people tap in at — add the first one to get started.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = components.EmptyState("No venues yet").Render(templ.WithChildren(ctx, templ_7745c5c3_Var10), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</section><section class=\"flex flex-col gap-4\"><div class=\"flex flex-wrap items-center justify-between gap-3\"><h2 class=\"font-display text-lg font-bold tracking-tight text-ink\">Departments</h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(v.Venues) > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "<a class=\"btn btn--primary\" href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var11 templ.SafeURL = templ.URL(v.AddDepartmentHref)
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var11)))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "\">Add a department</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.DepartmentsCapped {
				templ_7745c5c3_Var12 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "<p>Only the first ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var13 string
					templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(v.DepartmentLimit)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/pages/locations.templ`, Line: 190, Col: 42}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, " departments are shown.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneWarn, "This list is not complete").Render(templ.WithChildren(ctx, templ_7745c5c3_Var12), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if len(v.Departments) > 0 {
				for _, d := range v.Departments {
					templ_7745c5c3_Err = components.DepartmentRow(d).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else if v.Queried {
				templ_7745c5c3_Var14 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					if len(v.Venues) > 0 {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "    <p>This business does not use departments, which is perfectly normal — a bar or a small venue usually does not need them. Add one if some of your staff work different hours from the rest of the venue.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "     <p>Add a venue first — a department is part of one.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					return nil
				})
				templ_7745c5c3_Err = components.EmptyState("No departments").Render(templ.WithChildren(ctx, templ_7745c5c3_Var14), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "</section>            <section class=\"flex flex-col gap-4\"><div class=\"flex flex-wrap items-center justify-between gap-3\"><h2 class=\"font-display text-lg font-bold tracking-tight text-ink\">Plaques on the wall</h2></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.PlaquesCapped {
				templ_7745c5c3_Var15 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "<p>Only the first ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var16 string
					templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(v.PlaqueLimit)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/pages/locations.templ`, Line: 238, Col: 38}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, " plaques are shown.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneWarn, "This list is not complete").Render(templ.WithChildren(ctx, templ_7745c5c3_Var15), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if len(v.Mounted) > 0 {
				for _, p := range v.Mounted {
					templ_7745c5c3_Err = components.PlaqueRow(p).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else if v.PlaquesQueried {
				templ_7745c5c3_Var17 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					if len(v.Stock) > 0 {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "<p>You have plaques in stock below. Open one to mount it at a venue.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "   <p>No plaques have been loaded for this business yet. Tappa encodes each plaque and loads it here; ask us for the ones you need and they will appear in stock, ready to mount.</p>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					return nil
				})
				templ_7745c5c3_Err = components.EmptyState("No plaques are mounted").Render(templ.WithChildren(ctx, templ_7745c5c3_Var17), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "</section><section class=\"flex flex-col gap-4\"><div class=\"flex flex-wrap items-center justify-between gap-3\"><h2 class=\"font-display text-lg font-bold tracking-tight text-ink\">In stock</h2></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(v.Stock) > 0 {
				for _, p := range v.Stock {
					templ_7745c5c3_Err = components.PlaqueRow(p).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else if v.PlaquesQueried {
				templ_7745c5c3_Var18 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 48, "<p>Every plaque loaded for this business is on a wall or out of service. Ask us for spares — you need one in the box before you can replace a plaque that fails.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = components.EmptyState("Nothing in stock").Render(templ.WithChildren(ctx, templ_7745c5c3_Var18), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 49, "</section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(v.OutOfService) > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 50, "<section class=\"flex flex-col gap-4\"><div class=\"flex flex-wrap items-center justify-between gap-3\"><h2 class=\"font-display text-lg font-bold tracking-tight text-ink\">Out of service</h2></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Var19 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 51, "<p>A plaque that has been replaced, or reported lost, keeps its record: the taps it took still point at it. Taps on these are rejected.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = components.Notice(components.ToneWarn, "These are kept on purpose").Render(templ.WithChildren(ctx, templ_7745c5c3_Var19), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, p := range v.OutOfService {
					templ_7745c5c3_Err = components.PlaqueRow(p).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 52, "</section>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return nil
		})
		templ_7745c5c3_Err = PanelShell(v.PanelChrome).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// doneVenueHeading names what the page can SHOW, which is not the same as what the
// query string says happened.
//
// 🔴 EVERY HEADING HERE NAMES A STATE, NOT AN EVENT, and that is the M6-04 lesson
// applied rather than relearned. "Placement saved" was measured unbacked on the
// roster: a URL in a browser that had never posted anything rendered an action claim.
// The four words below say what the list beneath them SHOWS, which the same request
// read from the database — so a replayed address restates something true instead of
// inventing a change.
//
// 🔴 THE TWO REMOVAL WORDS ARE NOT AMONG THEM, AND THEY ARE HANDLED ELSEWHERE IN THIS
// FILE. doneVenueHeading is reached only for a word that backs itself; a removal is
// acknowledged by the RemovalReceipt branch at the top of AdminLocations, and
// removalHeading builds its text. Keeping the two apart is what stops a removal word
// from ever falling through to a heading printed on Done alone.
//
// ⚠️ THIS PARAGRAPH USED TO SAY A REMOVAL COULD NOT BE ACKNOWLEDGED AT ALL — "the
// claim is not made at all", "what confirms a removal is the list itself" — and by
// the time it was read again all three sentences were false. That was a real risk
// rather than an untidiness: C' is the ONLY guard against the F1 defect, and a
// maintainer who believed this comment could delete the RemovalReceipt path as dead
// code. The history, because it is the whole argument for the mechanism:
//
//	the words shipped UNBACKED and an audit measured the M6-05 defect again —
//	GET ?done=venue-deleted, in a browser that had never posted anything, rendered
//	"Venue removed — The venue has been removed";
//	they were then REMOVED, which was true but silent, so a manager who had just
//	deleted a venue saw no acknowledgement at all;
//	and they are now back and VERIFIED (user decision, 2026-08-09, reading C').
//	employees.templ allows an action claim on one condition — that the handler
//	checks it against a row THE SAME REQUEST READ — and after a deletion the
//	surviving row is the AUDIT ENTRY. So the claim is made, and it is checked.
//
// ClaimsARemoval says whether a word asserts something that no longer exists, and so
// may only be printed against a verified receipt.
//
// IT IS EXPORTED SO A TEST CAN COMPARE IT WITH THE HANDLER'S OWN LIST. Two lists that
// disagree would let a word be rendered on Done alone, which is the defect this whole
// mechanism replaces.
//
// 🔴 IT IS A FUNCTION RATHER THAN A CONDITION SPELLED OUT AT THE CALL SITE so the
// template cannot drift from the handler: internal/handler/locations.go holds the same
// two words in venueRemovalWords, and TestRemovalWords_AgreeBetweenHandlerAndTemplate
// requires the two lists to match.
func ClaimsARemoval(done string) bool {
	return done == "venue-deleted" || done == "department-deleted"
}

// removalHeading names what was removed, from the TRAIL rather than from the URL.
//
// THE NAME MAY BE EMPTY — a trail row from a future action with a different detail
// shape carries none — and then the heading says what happened without naming it,
// which is still true. It never falls back to anything the client supplied.
func removalHeading(done, name string) string {
	what := "Venue"
	if done == "department-deleted" {
		what = "Department"
	}
	if name == "" {
		return what + " removed"
	}
	return what + " removed: " + name
}

// ClaimsAPlaqueAct says whether a word asserts that something HAPPENED to a plaque,
// and so may only be printed against a verified trail entry.
//
// 🔴 IT IS A SEPARATE PREDICATE FROM ClaimsARemoval RATHER THAN A LONGER ONE,
// because the two are verified against DIFFERENT things: a removal against the
// removal's own audit row, a plaque act against the action that act writes. Merging
// them would make one list gate two mechanisms, and the next word added would
// inherit whichever check happened to be first.
//
// IT IS EXPORTED SO A TEST CAN COMPARE IT WITH THE HANDLER'S OWN LIST — the same
// reason ClaimsARemoval is. Two lists that disagree would let a word be rendered on
// Done alone, which is the defect this mechanism replaces.
func ClaimsAPlaqueAct(done string) bool {
	return done == "plaque-mounted" || done == "plaque-replaced" ||
		done == "plaque-unmounted"
}

// plaqueHeading names what the trail confirmed, from the TRAIL rather than from the
// URL.
//
// THE NAME MAY BE EMPTY — a trail row whose detail carries no `name` — and then the
// heading says what happened without naming anything, which is still true. It never
// falls back to something the client supplied: the uid in the address is only ever a
// lookup key.
func plaqueHeading(r components.PlaqueReceiptView) string {
	if r.Unmounted {
		if r.Name == "" {
			return "Plaque taken off the wall"
		}
		return "Plaque taken off the wall at " + r.Name
	}
	if r.Replaced {
		if r.Name == "" {
			return "Plaque replaced"
		}
		return "Plaque replaced — the new one is " + r.Name
	}
	if r.Name == "" {
		return "Plaque mounted"
	}
	return "Plaque mounted at " + r.Name
}

func doneVenueHeading(done string) string {
	switch done {
	case "venue-added":
		return "Venue added"
	case "department-added":
		return "Department added"
	case "department-saved":
		return "Department as it now stands"
	default:
		return "Venue as it now stands"
	}
}

func problemVenueHeading(problem string) string {
	switch problem {
	case "venue-in-use", "department-in-use":
		return "It is not empty any more"
	case "not-permitted":
		return "That is an owner's to remove"
	case "confirm-required", "confirm-stale":
		return "Nothing was removed"
	case "unreadable":
		return "We could not read that"
	case "unknown-venue":
		return "We could not find that venue"
	case "unknown-department":
		return "We could not find that department"
	case "unknown-plaque":
		return "We could not find that plaque"
	case "plaque-not-stock":
		return "That plaque is not in the box any more"
	case "plaque-not-active":
		return "That plaque is not on a wall any more"
	case "plaque-no-wall":
		return "There is nothing to take down"
	case "same-plaque":
		return "A plaque cannot replace itself"
	case "plaque-frozen":
		return "That plaque cannot be changed"
	default:
		return "We could not load your venues"
	}
}

var _ = templruntime.GeneratedTemplate
