// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/atknatk/tappa/web/templates/layout"

// Tap is THE screen: the one a wall plaque opens, several times a day, for
// someone with wet or gloved hands who is not here to use software.
//
// THE WHOLE DESIGN IS A LIST OF THINGS THAT ARE NOT HERE (CLAUDE.md §9, skill
// tappa-brand). No menu, no tabs, no settings, no history, no shift summary, no
// second action, nothing to scroll to. A greeting, a venue, a button.
//
// THE BUTTON IS DIRECTION-NEUTRAL and that is not laziness. Whether this tap is
// an in or an out is a computation over the employee's last OPEN entry (§5:
// toggle on the last open entry, never on the calendar day) — it belongs to the
// decision engine at POST time, and a page that predicted it would sometimes
// disagree with the confirmation screen a second later. The confirmation screen
// (M5-06) is where "Tapped in at 14:03" gets said, once it is true.
//
// .tap-button gives the target min-h-16 = 64px, which is the card's number and
// well past the 44px accessibility floor; it also honours prefers-reduced-motion
// (input.css). The form is a plain POST that works with JavaScript disabled —
// it simply carries no coordinates then, which §5 rows 6-7 already treat as a
// legitimate state (GPS is backup evidence, never a requirement).
//
// THE THREE COORDINATE FIELDS ARE EMPTY ON EVERY RENDER. web/static/js/tap.js
// fills them from ONE navigator.geolocation.getCurrentPosition call made when
// the button is pressed, and submits (§4.2: at the moment of a tap, never
// watched, never in the background). A refusal, a missing geolocation API or a
// timed-out fix leaves them empty and the tap proceeds.
//
// THE ONLY DYNAMIC VALUE IS THE SIGNED CONTEXT, and here is precisely what that
// does and does not mean — an audit decoded the field and found an earlier
// version of this comment claiming more than it delivers.
//
//	NOT in this HTML:  the chip's CMAC. It is checked on the server while the
//	                   page is built and never leaves it, so the page carries
//	                   the one-bit OUTCOME instead (tapcontext.go).
//	IN the HTML:       the tag uid and the counter. They are inside the signed
//	                   payload, base64 rather than hidden, and page script can
//	                   decode them. Neither is a secret — the chip prints both
//	                   in the address bar of this very page — but "tag and ctr
//	                   are not here" was simply false.
//
// What the signature buys is not concealment, it is INTEGRITY plus provenance:
// POST /api/checkin acts only on a context this server minted, for this
// session, recently.
//
// THE BUSINESS'S BRAND IS A SECOND, EXPLICIT PARAMETER (M10 WL-9), not a field of
// TapView: the view keeps its three fields, and b reaches the shell only -- the
// header (logo and co-brand line, or the wordmark) and the accent's stylesheet,
// which the button reads through its own class (user decisions D-C, K-2a, K-2b;
// ADR 0023 §2, §7). Nothing below the header changes with it: one greeting, one
// venue, one button, its word "Tap".
//
// THE GREETING AND THE BUTTON'S FACE ARE COMPONENTS OF THEIR OWN (TapHeading,
// TapButtonFace) so the Account editor's preview (M10 WL-7) can draw the same two
// without the form (ADR 0023 §2). Splitting them changed no byte of this screen
// (TestUnbrandedScreens_AreByteIdenticalToTheGolden). The two are JOINED rather than
// written as two lines because templ writes a space between two lines of a shell's
// block, and the docket always closed straight into the form.
func Tap(v TapView, b layout.Brand) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templ.Join(TapHeading(v.EmployeeName, v.LocationName), tapForm(v.TapContext)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.PageWithScript("Tap — Taptime", "/static/js/tap.js", b).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// tapForm is the tap's one form: the signed context, the three coordinate fields
// tap.js fills at the moment of the press (§4.2), and the button that submits them.
//
// THE ONE SPACE WRITTEN OUT after the last field is the space the form always had
// there: templ writes none between an element and a component call, and the golden
// holds the bytes from before the split. It changes nothing on screen -- the form
// lays its children out as a column, which drops the white space between them.
func tapForm(signedContext string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form method=\"post\" action=\"/api/checkin\" data-tap-form class=\"flex flex-col gap-4\"><input type=\"hidden\" name=\"ctx\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(signedContext)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/pages/tap.templ`, Line: 76, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"> <input type=\"hidden\" name=\"lat\" value=\"\" data-tap-lat> <input type=\"hidden\" name=\"lng\" value=\"\" data-tap-lng> <input type=\"hidden\" name=\"acc\" value=\"\" data-tap-acc>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/pages/tap.templ`, Line: 79, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TapButtonFace(TapButtonSubmits).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// TapHeading is the tap screen's docket: "Hello Maria" and the TAPPED venue, and
// nothing else. An empty venue renders without the line rather than with a blank
// one -- the plaque belongs to another business, or to no wall (ErrForeignLocation).
func TapHeading(employeeName, locationName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<section class=\"docket\"><p class=\"docket-label\">Tapping</p><h1 class=\"font-display text-3xl font-bold tracking-tight text-ink\">Hello ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(employeeName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/pages/tap.templ`, Line: 91, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if locationName != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<p class=\"mt-1 text-ink/70\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(locationName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/pages/tap.templ`, Line: 94, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// TapButtonUse is where the tap button's face is drawn. A closed set of two, and the
// zero value is the one that submits because the tap screen is the product; the
// preview's value has to be named.
type TapButtonUse int

const (
	// TapButtonSubmits is the tap screen's one button: the form's submit, which
	// web/static/js/tap.js finds by its data attribute.
	TapButtonSubmits TapButtonUse = iota
	// TapButtonPreview is the same face drawn by the Account editor's preview (M10
	// WL-7): type="button", no data attribute for tap.js to find, and nothing to
	// submit -- ADR 0023 §2 requires the preview to be unsendable.
	TapButtonPreview
)

// TapButtonFace is the tap button's face -- its class, which carries the 64 px target
// and the tenant accent's fill (ADR 0023 §2-§4), and its one word. A value outside
// the two above draws the preview's face: one that cannot submit.
func TapButtonFace(use TapButtonUse) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if use == TapButtonSubmits {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<button type=\"submit\" class=\"tap-button\" data-tap-button>Tap</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<button type=\"button\" class=\"tap-button\">Tap</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
