// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: policies.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ensureBaselinePolicy = `-- name: EnsureBaselinePolicy :exec
INSERT INTO policies (id, tenant_id, name, layer, enabled, created_by)
VALUES ($1, $2, $3, 'baseline', true, NULL)
ON CONFLICT (id) DO NOTHING
`

type EnsureBaselinePolicyParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
}

// Materialise one managed-baseline policy CONTAINER. layer is fixed to 'baseline'
// in the statement rather than taken as a parameter: this query exists for the
// Tappa-authored baseline only, and a caller that could pass 'tenant' would be
// able to author a tenant policy from the tap path. ('guardrail' is not spellable
// at all -- 00007's CHECK sees to that, which is what keeps a red line out of the
// database.)
//
// created_by is NULL: the author is Tappa's system provisioning, not a human
// admin (00007 documents exactly this case).
//
// ON CONFLICT (id) DO NOTHING is what makes a second tap free. It also means an
// EXISTING row is left exactly as it is -- including enabled=false. A tenant that
// switched a baseline statement off must not have it switched back on by someone
// walking up to a plaque.
//
// 🔴 THIS COMMENT USED TO SAY "and a hundred concurrent first taps produce one
// row". IT IS FALSE, AND THIS INSERT IS THE ONE THAT FAILS. Measured (M5-08
// audit, barrier-synchronised COMMITTING racers, a virgin key per attempt, five
// attempts per row):
//
//	policies            ON CONFLICT (id)                20 racers: 4 / 100 fail
//	                                                    40 racers: 9 / 200 fail
//	policies            ON CONFLICT (id, tenant_id)      8 racers: 10 / 40 fail
//	policy_versions     ON CONSTRAINT ..._no_key        20 racers: 19 / 100 fail
//	policy_versions     ON CONFLICT (id)  [the PK]      20 racers:  9 / 100 fail
//	policy_attachments  ON CONSTRAINT ..._resource_key  20 and 40 racers: 0 fail
//
// and through the REAL code path (policySets.forTenant against a virgin tenant),
// 40 racers produce 3-4 failures per 200, every one logged as:
//
//	materialise baseline: ensure baseline policy "...": duplicate key value
//	violates unique constraint "policies_id_tenant_key" (SQLSTATE 23505)
//
// THE RULE IS "A NON-ARBITER UNIQUE INDEX", NOT "THE PRIMARY KEY". ON CONFLICT
// arbitrates on ONE index; the speculative insertion can still trip any OTHER
// unique index on the row. policies carries TWO: policies_pkey (id) and
// policies_id_tenant_key (id, tenant_id) -- the latter added by 00007 as a
// composite FK target. Arbitrating on either one leaves the other exposed, which
// is why both columns of the table above fail and why swapping the target only
// moves the collision. policy_attachments never fails for a structural reason
// instead: it does not supply id at all (see its INSERT), so gen_random_uuid()
// gives every racer a distinct primary key and there is no second index to trip.
//
// ⚠️ NO WORKING ARBITER CHOICE IS KNOWN. An earlier version of this comment
// recommended "arbitrate on the PRIMARY KEY"; that is RETRACTED -- measured, PK
// arbitration on policy_versions still fails 9 / 100, on policy_versions_no_key.
// A real fix has to come from somewhere else (retry on 23505, an upsert that
// names both indexes, or provisioning the baseline once at sign-up so the tap
// path never races -- M7-03's job).
//
// 🔬 METHOD, because this class is easy to measure wrongly and an earlier
// measurement in this very comment reported "0 failures" for the top row:
//   - the race only exists once a COMPETING TRANSACTION COMMITS -- a harness
//     whose racers roll back cannot see it at all;
//   - it is a LOW-PROBABILITY event (~4% of inserts here), so ONE green run
//     proves nothing: run many attempts, each with a VIRGIN key;
//   - the probe must supply ids the way PRODUCTION does. The earlier probe handed
//     every racer the same policy_attachments id, which production never does,
//     and so "measured" a failure that cannot occur.
//
// IT IS FAIL-SAFE, NOT SILENT: a losing racer's tap falls back to a
// guardrail-only decision, so the record is still written (section 4.6) and is
// flagged rather than counted. NOT FIXED HERE -- policyset.go is outside the
// M5-08 diff and the fix belongs with M7-03's provisioning; the existing race
// test uses 8 racers, below the rate at which this shows up.
//
// ON CONFLICT (id) DO NOTHING still makes a second tap free, and it leaves an
// EXISTING row exactly as it is -- including enabled=false. A tenant that
// switched a baseline statement off must not have it switched back on by someone
// walking up to a plaque.
func (q *Queries) EnsureBaselinePolicy(ctx context.Context, arg EnsureBaselinePolicyParams) error {
	_, err := q.db.Exec(ctx, ensureBaselinePolicy, arg.ID, arg.TenantID, arg.Name)
	return err
}

const ensureBaselinePolicyVersion = `-- name: EnsureBaselinePolicyVersion :exec
INSERT INTO policy_versions (id, tenant_id, policy_id, version_no, document, created_by)
VALUES ($1, $2, $3, 1, $4, NULL)
ON CONFLICT ON CONSTRAINT policy_versions_no_key DO NOTHING
`

type EnsureBaselinePolicyVersionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	PolicyID uuid.UUID
	Document []byte
}

// Materialise version 1 of a managed-baseline policy's document.
//
// VERSION 1, ALWAYS, and never an update. policy_versions is APPEND-ONLY at two
// levels (REVOKE UPDATE/DELETE plus a trigger that stops even the owner), because
// every transaction pins the version that decided it: rewriting a version would
// rewrite why a past, immutable record was flagged. So when the shipped baseline
// changes, the correct move is a NEW version appended after the tenant accepts it
// (internal/policy.BaselineVersion says so, and M7-03 owns the flow) -- not an
// edit here. This statement therefore does nothing at all once version 1 exists,
// whatever the binary now says.
//
// The conflict target is the (tenant_id, policy_id, version_no) key rather than
// the primary key, so it holds even if a caller passed a different id for the
// same version -- the row that exists wins either way.
func (q *Queries) EnsureBaselinePolicyVersion(ctx context.Context, arg EnsureBaselinePolicyVersionParams) error {
	_, err := q.db.Exec(ctx, ensureBaselinePolicyVersion,
		arg.ID,
		arg.TenantID,
		arg.PolicyID,
		arg.Document,
	)
	return err
}

const ensurePolicyAttachment = `-- name: EnsurePolicyAttachment :exec
INSERT INTO policy_attachments (tenant_id, policy_id, resource)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT policy_attachments_resource_key DO NOTHING
`

type EnsurePolicyAttachmentParams struct {
	TenantID uuid.UUID
	PolicyID uuid.UUID
	Resource string
}

// Bind a materialised baseline policy to a resource ('*' tenant-wide for every
// shipped baseline document today).
//
// ⚠️ NOTHING READS THESE ROWS YET, and writing them anyway is a decision rather
// than an oversight. policy.Evaluate scopes a statement by the Resource patterns
// INSIDE its document, not by attachments, so the Set assembled for a tap is
// identical with or without them. They are written because a materialised policy
// with no attachment row is a half-provisioned policy, and the panel (M6-09) and
// provisioning (M7-03) will both read attachments to answer "where does this
// apply" -- a question that would otherwise get the wrong answer for every tenant
// provisioned by this path.
func (q *Queries) EnsurePolicyAttachment(ctx context.Context, arg EnsurePolicyAttachmentParams) error {
	_, err := q.db.Exec(ctx, ensurePolicyAttachment, arg.TenantID, arg.PolicyID, arg.Resource)
	return err
}

const listPolicyAttachments = `-- name: ListPolicyAttachments :many
SELECT policy_id, resource
FROM policy_attachments
WHERE tenant_id = $1
ORDER BY policy_id, resource
LIMIT $2
`

type ListPolicyAttachmentsParams struct {
	TenantID uuid.UUID
	RowLimit int32
}

type ListPolicyAttachmentsRow struct {
	PolicyID uuid.UUID
	Resource string
}

// Where each of the tenant's policies is bound: 'location/<id>', 'department/<id>',
// 'employee/<id>' or '*' (tenant-wide).
//
// WHAT THESE ROWS DO AND DO NOT DECIDE, because the screen that shows them must
// not imply the wrong one. policy.Evaluate scopes a statement by the Resource
// patterns INSIDE its document, NOT by these rows -- EnsurePolicyAttachment's own
// comment says so and the Set assembled for a tap is identical with or without
// them. They record where a policy was BOUND at provisioning time; the rules that
// actually run carry their own resource patterns. The screen prints both and says
// which one the engine reads.
//
// TENANT SCOPE (section 4.5): explicit tenant_id beside RLS, like every other read.
func (q *Queries) ListPolicyAttachments(ctx context.Context, arg ListPolicyAttachmentsParams) ([]ListPolicyAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listPolicyAttachments, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPolicyAttachmentsRow{}
	for rows.Next() {
		var i ListPolicyAttachmentsRow
		if err := rows.Scan(&i.PolicyID, &i.Resource); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicySet = `-- name: ListPolicySet :many

SELECT DISTINCT ON (p.id)
       p.id AS policy_id, p.name, p.layer, p.enabled,
       v.id AS version_id, v.version_no, v.document
FROM policies p
JOIN policy_versions v
  ON v.tenant_id = p.tenant_id
 AND v.policy_id = p.id
WHERE p.tenant_id = $1
ORDER BY p.id, v.version_no DESC
`

type ListPolicySetRow struct {
	PolicyID  uuid.UUID
	Name      string
	Layer     string
	Enabled   bool
	VersionID uuid.UUID
	VersionNo int32
	Document  []byte
}

// policies.sql -- reading a tenant's stored policy layer, and MATERIALISING the
// Tappa-managed baseline into it.
//
// WHY THESE QUERIES EXIST AT ALL, measured before they were written. The
// decision engine's rows 6 and 7 of CLAUDE.md section 5 -- the ordinary `ok` and
// the ordinary `flag`, i.e. the MAIN PATH of the whole product -- are BASELINE
// decisions, and migration 00008 requires a baseline decision to name a real
// policy_versions row: the consistency CHECK demands policy_version_id IS NOT
// NULL for layer 'baseline', and the composite FK demands it resolve to a
// same-tenant version. Measured against the dev database, as tappa_app, for the
// seeded Kebab Factory tenant:
//
//	policies = 0, policy_versions = 0
//	INSERT ... policy_layer='baseline', policy_version_id=<any uuid>
//	  -> ERROR 23503 transactions_policy_version_fk
//
// So before this file existed, an ordinary approved check-in COULD NOT BE
// WRITTEN. That is a section 4.6 record loss on the most common path there is,
// and it is not hypothetical: M7-03 (provisioning) is the task that was supposed
// to write these rows and it has not been done.
//
// THE FIX IS TO MATERIALISE, NOT TO SKIP. The alternative -- evaluate with no
// baseline -- writes the record but sends EVERY tap to the fail-to-review default,
// which is a silent, permanent degradation dressed as safety. So the tap path
// materialises the baseline the first time it needs it, idempotently, and M7-03
// takes the job over at provisioning time (see internal/domain/checkin).
//
// IDEMPOTENCY IS ANCHORED ON CONSTRAINTS THAT ALREADY EXIST, so no migration was
// needed -- but the three statements below do NOT all use the same one, and an
// earlier version of this comment said "the primary key" for all three, which was
// wrong for two of them:
//
//	policies            ON CONFLICT (id)                       -- the PRIMARY KEY
//	policy_versions     ON CONFLICT ON CONSTRAINT
//	                    policy_versions_no_key                 -- UNIQUE (tenant_id, policy_id, version_no)
//	policy_attachments  ON CONFLICT ON CONSTRAINT
//	                    policy_attachments_resource_key        -- UNIQUE (tenant_id, policy_id, resource)
//
// policies has no (tenant_id, name) key, which is why its id is DERIVED from
// (tenant, baseline document name) with uuid v5: that makes its primary key a
// usable conflict target. The other two already had a natural key to conflict on.
// All three keep this an INSERT-ONLY change to append-only data: policy_versions
// is append-only by privilege AND by trigger (00007), so "write it again" must be
// a no-op rather than a second row.
//
// TENANT SCOPE (section 4.5, belt + braces): every statement carries an explicit
// tenant_id and runs inside db.(*DB).WithTenant, whose RLS WITH CHECK refuses a
// row for any other tenant.
// The tenant's stored policy layer: one row per policy, carrying its LATEST
// version's id and document.
//
// DISTINCT ON (p.id) with ORDER BY p.id, v.version_no DESC takes the highest
// version_no per policy -- "latest" is the version number, never created_at,
// because version_no is the monotonic sequence 00007 defines and two versions can
// share a timestamp. A policy with no version yet is NOT returned (an inner
// join): a policy without a document decides nothing, and returning it would let
// a caller pin a policy_version_id it does not have.
//
// enabled IS RETURNED, NOT FILTERED. The caller needs to tell "this tenant turned
// this baseline statement OFF" (leave it out of the Set) apart from "this baseline
// statement was never materialised" (materialise it) -- a WHERE enabled would make
// those two indistinguishable and turn a deliberate opt-out into a permanent
// re-provisioning loop. Disabling is the tenant's off switch and is never a
// delete (section 4.6, 00007).
//
// ROW ORDER IS NOT THE EVALUATION ORDER. This comes back ordered by a random
// uuid; the evaluator's tiebreak needs baseline-in-document-order, so the caller
// re-orders against the canonical list in internal/policy. Relying on this order
// would make which sid gets reported depend on uuid generation.
func (q *Queries) ListPolicySet(ctx context.Context, tenantID uuid.UUID) ([]ListPolicySetRow, error) {
	rows, err := q.db.Query(ctx, listPolicySet, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPolicySetRow{}
	for rows.Next() {
		var i ListPolicySetRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.Name,
			&i.Layer,
			&i.Enabled,
			&i.VersionID,
			&i.VersionNo,
			&i.Document,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyVersions = `-- name: ListPolicyVersions :many
SELECT p.id AS policy_id, p.name, p.layer, p.enabled,
       v.id AS version_id, v.version_no, v.created_at AS version_created_at,
       v.created_by, a.full_name AS author_name,
       -- COALESCE, NOT A BARE octet_length, AND IT IS THE OUTER JOIN THAT MAKES IT
       -- NECESSARY. sqlc types ` + "`" + `octet_length(...)::int` + "`" + ` as NOT NULL, but a policy
       -- with no version produces a NULL here and the generated Scan would fail at
       -- run time on exactly the half-provisioned row this query was widened to
       -- see. 0 is unambiguous: version_id is NULL on the same row, and a real
       -- document can never be 0 bytes (NOT NULL jsonb; the smallest legal value
       -- is ` + "`" + `{}` + "`" + `, which is 2 -- 18 355 such rows exist in the development
       -- database, so the floor is measured rather than assumed).
       COALESCE(octet_length(v.document::text), 0)::int AS document_bytes
FROM policies p
LEFT JOIN policy_versions v
       ON v.tenant_id = $1 AND v.policy_id = p.id
LEFT JOIN admin_users a
       ON a.tenant_id = $1 AND a.id = v.created_by
WHERE p.tenant_id = $1
ORDER BY p.name, p.id, v.version_no DESC
LIMIT $2
`

type ListPolicyVersionsParams struct {
	TenantID uuid.UUID
	RowLimit int32
}

type ListPolicyVersionsRow struct {
	PolicyID         uuid.UUID
	Name             string
	Layer            string
	Enabled          bool
	VersionID        *uuid.UUID
	VersionNo        *int32
	VersionCreatedAt *time.Time
	CreatedBy        *uuid.UUID
	AuthorName       *string
	DocumentBytes    int32
}

// The tenant's policy VERSION HISTORY: who wrote which version of which policy,
// and when. The panel's Policies screen (M6-09 phase A) is the only caller.
//
// IT CARRIES NO document COLUMN, AND THAT IS A BOUND RATHER THAN AN OMISSION.
// ListPolicySet already returns the LATEST document per policy, which is what the
// screen renders as "the rules in force". Returning every OLD document here would
// be unbounded in a way a LIMIT cannot fix: internal/policy.DefaultLimits bounds
// documents per tenant, versions per policy AND bytes per document separately, so a
// ROW cap still leaves the BYTES uncapped -- a page of the largest legal document is
// megabytes into one panel request.
// octet_length is returned instead, so the screen can say how big a version is
// without carrying it. Reading an OLD version's body needs its own bounded route
// and is M6-09 phase B (see the delivery note on the card).
//
// LEFT JOIN policy_versions, NOT AN INNER ONE, and this is the difference from
// ListPolicySet. That query inner-joins on purpose (a policy with no document
// decides nothing, so the decision engine must not see it). The PANEL has the
// opposite need: a policies row with no version is a HALF-PROVISIONED policy, and
// it is not hypothetical -- measured against the development database on
// 2026-08-11, `SELECT count(*) FROM policies p WHERE NOT EXISTS (SELECT 1 FROM
// policy_versions v WHERE v.policy_id = p.id AND v.tenant_id = p.tenant_id)`
// returned 2005 rows. Without the outer join the screen would report that state as
// "never provisioned", which is a different thing and points at a different fix.
//
// created_by IS FK-LESS (00007 defers the admin FK to M6/M7), so the author is
// resolved by an explicit LEFT JOIN rather than by a constraint. THREE outcomes,
// and the screen tells them apart:
//
//	created_by IS NULL                  -> Tappa's system provisioning wrote it.
//	created_by set, full_name present   -> that admin wrote it.
//	created_by set, full_name NULL      -> the id resolves to nobody this tenant
//	                                       can see. RLS is doing its job (a
//	                                       cross-tenant id CANNOT be resolved
//	                                       here, by design), and the screen says
//	                                       "not resolvable" rather than printing
//	                                       a name it does not have.
//
// TENANT SCOPE (section 4.5, belt + braces): the subject and BOTH joined tables
// bind tenant_id to @tenant_id explicitly, rather than chaining off p.tenant_id.
// The chained form is equivalent under RLS and is one refactor away from not
// being: a joined predicate that stands in for the subject's is exactly the shape
// internal/domain/tenant/query_test.go's block scan was rebuilt to catch.
//
// ORDER IS (name, id, version_no DESC) so the newest version of a policy comes
// first within its policy, and the policies themselves arrive in a stable,
// human order. Unlike ListPolicySet this order IS meaningful -- but it is a
// DISPLAY order, never an evaluation order; the evaluator's canonical ordering
// lives in internal/policy and the panel re-derives it from there.
func (q *Queries) ListPolicyVersions(ctx context.Context, arg ListPolicyVersionsParams) ([]ListPolicyVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPolicyVersions, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPolicyVersionsRow{}
	for rows.Next() {
		var i ListPolicyVersionsRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.Name,
			&i.Layer,
			&i.Enabled,
			&i.VersionID,
			&i.VersionNo,
			&i.VersionCreatedAt,
			&i.CreatedBy,
			&i.AuthorName,
			&i.DocumentBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
