// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenants.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    id, name, vat_number, business_type, structure, timezone,
    vat_verified, vat_checked_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
)
RETURNING id, name, vat_number, business_type, structure, plan, timezone,
          price_per_employee_month, vat_verified, vat_checked_at, created_at
`

type CreateTenantParams struct {
	ID           uuid.UUID
	Name         string
	VatNumber    string
	BusinessType string
	Structure    string
	Timezone     string
	VatVerified  *bool
	VatCheckedAt *time.Time
}

type CreateTenantRow struct {
	ID                    uuid.UUID
	Name                  string
	VatNumber             string
	BusinessType          string
	Structure             string
	Plan                  string
	Timezone              string
	PricePerEmployeeMonth pgtype.Numeric
	VatVerified           *bool
	VatCheckedAt          *time.Time
	CreatedAt             time.Time
}

// Creates a business. THE FIRST WRITE INTO `tenants` THAT ANY APPLICATION PATH IN
// THIS PRODUCT HAS EVER MADE (M7-02): until this query, `INSERT INTO tenants`
// appeared only in test/fixtures/seed.sql and in test helpers, which is the fact
// migration 00011 built a risk boundary on and said would expire here.
//
// 🔴 THE CALLER SUPPLIES `id`, AND IT IS NOT A STYLE CHOICE -- IT IS THE ONLY SHAPE
// THAT CAN WORK. `tenants` is the one table whose RLS policy scopes on `id` rather
// than on `tenant_id` (migration 00001, ADR 0002 madde 5), so the WITH CHECK compares
// the inserted `id` against app.tenant_id. A row taking the column DEFAULT
// gen_random_uuid() would produce an id the transaction's context has never heard
// of, and every such INSERT fails the policy. Migration 00016 says the same from the
// privilege side and is why `id` is in the INSERT grant at all: "without INSERT on
// `id` the application could not create a tenant".
//
// ⚠️ SO THE TENANT CONTEXT IS SET TO A ROW THAT DOES NOT EXIST YET, which reads
// alarming and is the safest possible thing to do with an unauthenticated caller.
// The whole transaction runs under app.tenant_id = <the new id>, and under that
// context RLS makes EVERY table in the schema empty: there is no row anywhere whose
// tenant_id equals a uuid nothing has ever used. The wizard therefore runs with
// strictly LESS reach than any authenticated panel request, not more.
//
// 🔴 AND THE VALUE IS NEVER THE CALLER'S. internal/domain/signup mints it with
// uuid.NewRandom (crypto/rand) inside the provisioning call; no field of the sign-up
// form, no cookie and no query parameter reaches it. That is what stops the obvious
// attack on the paragraph above -- a stranger naming somebody else's tenant id and
// getting a transaction scoped to it. TestSignupProvision_TenantIDIsNeverTakenFromTheRequest
// asserts it at the boundary.
//
// THREE COLUMNS ARE ABSENT FROM THE INSERT LIST AND TAKE THEIR DEFAULTS: `plan`
// ('founding'), `price_per_employee_month` (1.50) and `created_at` (now()). That is
// migration 00016's decision, enforced by privilege rather than by this file --
// tappa_app has no INSERT on any of the three, so naming one here would not compile
// against the database. A new customer gets the founding offer and the published
// price, which is exactly what the landing page sells.
//
// vat_number is globally UNIQUE (migration 00001), so a second registration of the
// same business fails with 23505 rather than creating a duplicate tenant. The
// boundary turns that into a plain sentence on the form; it is NOT an enumeration
// concern worth hiding, because a VAT number is public data that anyone can put into
// VIES.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.VatNumber,
		arg.BusinessType,
		arg.Structure,
		arg.Timezone,
		arg.VatVerified,
		arg.VatCheckedAt,
	)
	var i CreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VatNumber,
		&i.BusinessType,
		&i.Structure,
		&i.Plan,
		&i.Timezone,
		&i.PricePerEmployeeMonth,
		&i.VatVerified,
		&i.VatCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantClock = `-- name: GetTenantClock :one

SELECT id, name, timezone
FROM tenants
WHERE id = $1
`

type GetTenantClockRow struct {
	ID       uuid.UUID
	Name     string
	Timezone string
}

// tenants.sql -- reads of the tenant's own row.
//
// TENANT SCOPE (CLAUDE.md section 4.5, belt + braces on RLS): the query carries an
// explicit tenant_id predicate and runs inside db.(*DB).WithTenant. The tenant id
// comes from a resolver or a verified session (ADR 0002 madde 7), never from the
// client.
//
// This file exists because M6-03 needed ONE fact -- what "today" means for this
// business -- and there was nowhere honest to put it. The tap path never needed
// it: every timestamp it handles is an instant, and CLAUDE.md section 6 keeps
// instants in UTC. A DAY is the first thing this product has had to render that
// is not an instant, and a day has no meaning without a zone.
// The tenant's timezone -- the zone the panel's "day" is measured in.
//
// 🔴 WHY THE PANEL CANNOT USE THE SERVER'S ZONE, OR THE BROWSER'S. Section 6 says
// everything in the database is UTC and conversion happens at render; this query is
// the render layer asking WHICH zone to convert to. Using the server's would make
// the same business see a different day depending on where the VPS is; using the
// browser's would let a client decide which records it is shown, and the client is
// not the authority on anything here.
//
// IT MATTERS MOST FOR THE OVERNIGHT SHIFT, which is the case section 5 keeps
// returning to: Rusty Bar works 18:00-02:00, so a 02:00 check-out falls on the
// NEXT calendar day in Malta and belongs to the next day's page. That is a
// property of the day boundary, not a bug to be corrected -- the shift-aware view
// is M6-07's report, and this query is what makes the boundary at least honest
// and consistent rather than accidental.
//
// timezone is NOT NULL DEFAULT 'Europe/Malta' (migration 0001), so this never
// returns an empty zone for a row that exists; the caller still falls back to UTC
// if the stored name is one the Go runtime cannot load, because an unparseable
// zone must not cost the manager their page.
func (q *Queries) GetTenantClock(ctx context.Context, tenantID uuid.UUID) (GetTenantClockRow, error) {
	row := q.db.QueryRow(ctx, getTenantClock, tenantID)
	var i GetTenantClockRow
	err := row.Scan(&i.ID, &i.Name, &i.Timezone)
	return i, err
}
