// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLastOpenTransaction = `-- name: GetLastOpenTransaction :one

SELECT id, tenant_id, employee_id, location_id, department_id, tag_uid, ctr,
       type, occurred_at, source_ip, ip_match, gps_lat, gps_lng, gps_match,
       sun_valid, trust, verdict, note, channel, entered_by, practice, queued,
       created_at, policy_version_id, matched_sid, policy_layer, policy_context
FROM transactions t
WHERE t.tenant_id = $1
  AND t.employee_id = $2
  AND t.type = 'in'
  AND NOT EXISTS (
      SELECT 1
      FROM transactions o
      WHERE o.tenant_id = t.tenant_id
        AND o.employee_id = t.employee_id
        AND o.type = 'out'
        AND o.occurred_at > t.occurred_at
  )
ORDER BY t.occurred_at DESC
LIMIT 1
`

type GetLastOpenTransactionParams struct {
	TenantID   uuid.UUID
	EmployeeID *uuid.UUID
}

// transactions.sql -- tenant-scoped reads and the single append-only write for
// the product's core record. Every query carries an explicit tenant_id filter
// (CLAUDE.md section 4.5, belt + braces on RLS). transactions is IMMUTABLE
// (section 4.3): no UPDATE/DELETE queries exist here by design -- corrections are
// a new row + audit_log, and the FLAGGED review flow writes to
// transaction_reviews, never here.
//
// POLICY DECISION COLUMNS (M3-07, migration 0008): policy_version_id, matched_sid,
// policy_layer and policy_context bind each record to WHY it got its verdict. They
// are part of every column list below so this file keeps returning the full store
// Transaction model (additive). The tap engine's caller (M5-05) SUPPLIES the values
// from policy.Decision + a section 4.7-safe policy.Context snapshot (a GPS DISTANCE,
// never a raw coordinate); the DB CHECK transactions_policy_decision_consistent
// guarantees the four columns are mutually consistent or all absent.
// Direction toggle basis (CLAUDE.md section 5): the person's last OPEN check-in,
// i.e. the most recent type='in' with no later type='out'. If a row is found the
// next tap is 'out'; if none (pgx.ErrNoRows) the next tap is 'in'. Ordering is by
// occurred_at, NOT by calendar day, so the overnight shift (Rusty Bar 18:00-02:00)
// toggles correctly at a 02:00 exit. Neutral on verdict: 'in' only ever appears on
// decided taps (reject/ignored carry NULL type), so filtering on the direction
// column is enough; whether a flagged 'in' counts is a domain (M3) call, not the
// store's. Uses the (tenant_id, employee_id, occurred_at DESC) index.
func (q *Queries) GetLastOpenTransaction(ctx context.Context, arg GetLastOpenTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getLastOpenTransaction, arg.TenantID, arg.EmployeeID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.LocationID,
		&i.DepartmentID,
		&i.TagUid,
		&i.Ctr,
		&i.Type,
		&i.OccurredAt,
		&i.SourceIp,
		&i.IpMatch,
		&i.GpsLat,
		&i.GpsLng,
		&i.GpsMatch,
		&i.SunValid,
		&i.Trust,
		&i.Verdict,
		&i.Note,
		&i.Channel,
		&i.EnteredBy,
		&i.Practice,
		&i.Queued,
		&i.CreatedAt,
		&i.PolicyVersionID,
		&i.MatchedSid,
		&i.PolicyLayer,
		&i.PolicyContext,
	)
	return i, err
}

const getLastTransactionForEmployee = `-- name: GetLastTransactionForEmployee :one
SELECT id, tenant_id, employee_id, location_id, department_id, tag_uid, ctr,
       type, occurred_at, source_ip, ip_match, gps_lat, gps_lng, gps_match,
       sun_valid, trust, verdict, note, channel, entered_by, practice, queued,
       created_at, policy_version_id, matched_sid, policy_layer, policy_context
FROM transactions
WHERE tenant_id = $1
  AND employee_id = $2
ORDER BY occurred_at DESC
LIMIT 1
`

type GetLastTransactionForEmployeeParams struct {
	TenantID   uuid.UUID
	EmployeeID *uuid.UUID
}

// Debounce basis (CLAUDE.md section 5, row 5): the person's single most recent
// tap. Debounce is PER-PERSON, not per-tag, so a queue of different people can
// tap the same wall plaque back to back. The domain compares this row's
// occurred_at with the new tap's time against the 60s window.
func (q *Queries) GetLastTransactionForEmployee(ctx context.Context, arg GetLastTransactionForEmployeeParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getLastTransactionForEmployee, arg.TenantID, arg.EmployeeID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.LocationID,
		&i.DepartmentID,
		&i.TagUid,
		&i.Ctr,
		&i.Type,
		&i.OccurredAt,
		&i.SourceIp,
		&i.IpMatch,
		&i.GpsLat,
		&i.GpsLng,
		&i.GpsMatch,
		&i.SunValid,
		&i.Trust,
		&i.Verdict,
		&i.Note,
		&i.Channel,
		&i.EnteredBy,
		&i.Practice,
		&i.Queued,
		&i.CreatedAt,
		&i.PolicyVersionID,
		&i.MatchedSid,
		&i.PolicyLayer,
		&i.PolicyContext,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    tenant_id, employee_id, location_id, department_id, tag_uid, ctr, type,
    occurred_at, source_ip, ip_match, gps_lat, gps_lng, gps_match, sun_valid,
    trust, verdict, note, channel, entered_by, practice, queued,
    policy_version_id, matched_sid, policy_layer, policy_context
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21,
    $22, $23, $24, $25
)
RETURNING id, tenant_id, employee_id, location_id, department_id, tag_uid, ctr,
          type, occurred_at, source_ip, ip_match, gps_lat, gps_lng, gps_match,
          sun_valid, trust, verdict, note, channel, entered_by, practice, queued,
          created_at, policy_version_id, matched_sid, policy_layer, policy_context
`

type InsertTransactionParams struct {
	TenantID        uuid.UUID
	EmployeeID      *uuid.UUID
	LocationID      *uuid.UUID
	DepartmentID    *uuid.UUID
	TagUid          *string
	Ctr             *int32
	Type            *string
	OccurredAt      time.Time
	SourceIp        *netip.Addr
	IpMatch         *bool
	GpsLat          pgtype.Numeric
	GpsLng          pgtype.Numeric
	GpsMatch        *bool
	SunValid        *bool
	Trust           *int16
	Verdict         string
	Note            *string
	Channel         string
	EnteredBy       *uuid.UUID
	Practice        bool
	Queued          bool
	PolicyVersionID *uuid.UUID
	MatchedSid      *string
	PolicyLayer     *string
	PolicyContext   []byte
}

// THE single write path. id and created_at use DB defaults; every other column
// is set by the tap engine, including practice and queued (no silent default is
// relied on for those two -- the engine states them). tenant_id is provided
// explicitly and WITH CHECK confirms it matches the context (section 4.5).
// employee_id/location_id/department_id/tag_uid/ctr are nullable so a
// context-less reject (stolen plaque, no session) is still recorded -- section
// 4.6, a record is never lost.
//
// The four POLICY-DECISION columns (M3-07) are also written here so the record
// carries WHY it got its verdict: policy_version_id (the pinned append-only version,
// NULL for a guardrail/default decision), matched_sid (the deciding sid --
// MACHINE-FILTERABLE, "sys:..." | tenant sid | "default"), policy_layer
// (guardrail|baseline|tenant) and policy_context (the section 4.7-safe input
// snapshot). The caller passes them from policy.Decision; passing all four NULL is
// valid too (the consistency CHECK permits the all-absent state, section 4.6).
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.TenantID,
		arg.EmployeeID,
		arg.LocationID,
		arg.DepartmentID,
		arg.TagUid,
		arg.Ctr,
		arg.Type,
		arg.OccurredAt,
		arg.SourceIp,
		arg.IpMatch,
		arg.GpsLat,
		arg.GpsLng,
		arg.GpsMatch,
		arg.SunValid,
		arg.Trust,
		arg.Verdict,
		arg.Note,
		arg.Channel,
		arg.EnteredBy,
		arg.Practice,
		arg.Queued,
		arg.PolicyVersionID,
		arg.MatchedSid,
		arg.PolicyLayer,
		arg.PolicyContext,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.LocationID,
		&i.DepartmentID,
		&i.TagUid,
		&i.Ctr,
		&i.Type,
		&i.OccurredAt,
		&i.SourceIp,
		&i.IpMatch,
		&i.GpsLat,
		&i.GpsLng,
		&i.GpsMatch,
		&i.SunValid,
		&i.Trust,
		&i.Verdict,
		&i.Note,
		&i.Channel,
		&i.EnteredBy,
		&i.Practice,
		&i.Queued,
		&i.CreatedAt,
		&i.PolicyVersionID,
		&i.MatchedSid,
		&i.PolicyLayer,
		&i.PolicyContext,
	)
	return i, err
}
