package db

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// TxFunc runs inside a tenant-scoped transaction. It receives the pgx.Tx so it
// can issue queries.
//
// NOTE (card deviation, see docs/plan/m1-veri-katmani.md M1-07 correction
// block): the M1-07 card typed this callback as func(context.Context,
// store.Querier) error. The store package is generated by sqlc in M1-08 and does
// not exist yet, so importing it here would not compile. We take pgx.Tx instead;
// M1-08 wraps it (store.New(tx)) either inside a future overload or at the call
// site. pgx.Tx is defined by the producer, but it is the minimal, correct handle
// the consumer needs today.
type TxFunc func(ctx context.Context, tx pgx.Tx) error

// WithTenant opens a transaction, establishes the tenant context, runs fn inside
// that transaction, and commits on success. On error it rolls back; on panic it
// rolls back and re-panics. It is the single structural guarantee that every
// query runs under the right tenant (CLAUDE.md §4.5, ADR 0002 madde 2).
//
// The context is set with set_config('app.tenant_id', $1, true): the third
// argument true makes it transaction-local (the SET LOCAL equivalent that
// accepts a bound parameter), so it is cleared when the transaction ends and
// NEVER leaks back onto the pooled connection. SET LOCAL cannot bind $1, and the
// tenant id is bound as a parameter — never concatenated into SQL.
//
// RLS policies wrap current_setting('app.tenant_id', true) in NULLIF over the
// empty-string literal, so both an unset context and an empty-string context
// collapse to NULL (ADR 0002 madde 3). That is fail-closed but silent (0 rows)
// when the context is missing; WithTenant is the compensation the ADR names — it
// makes running a query without the context impossible through this API.
func (d *DB) WithTenant(ctx context.Context, tenantID uuid.UUID, fn TxFunc) (err error) {
	// Refuse the nil UUID: it is a valid uuid literal, so it would silently
	// scope every query to a non-existent "zero tenant" (0 rows via RLS)
	// instead of failing loudly. This is a programming error, caught before we
	// touch the pool.
	if tenantID == uuid.Nil {
		return fmt.Errorf("db: WithTenant: refusing to scope to the nil tenant")
	}

	tx, err := d.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("db: begin tx: %w", err)
	}

	// Any early return or panic past this point must roll back so the
	// connection returns to the pool clean. Rollback uses a background context
	// because ctx may already be cancelled — otherwise the rollback itself
	// would be skipped and the transaction would be released mid-flight.
	defer func() {
		if p := recover(); p != nil {
			_ = tx.Rollback(context.Background())
			panic(p)
		}
		if err != nil {
			_ = tx.Rollback(context.Background())
		}
	}()

	if _, err = tx.Exec(ctx, "SELECT set_config('app.tenant_id', $1, true)", tenantID.String()); err != nil {
		return fmt.Errorf("db: set tenant context: %w", err)
	}

	if err = fn(ctx, tx); err != nil {
		// Return fn's error verbatim so callers can errors.Is/As it; the
		// deferred rollback undoes the transaction.
		return err
	}

	if err = tx.Commit(ctx); err != nil {
		return fmt.Errorf("db: commit tx: %w", err)
	}
	return nil
}
